export enum SagaState {
  INITIATED = 'INITIATED',
  DEBIT_PENDING = 'DEBIT_PENDING',
  DEBIT_COMPLETE = 'DEBIT_COMPLETE',
  CREDIT_PENDING = 'CREDIT_PENDING',
  COMPLETED = 'COMPLETED',
  COMPENSATING = 'COMPENSATING',
  COMPENSATED = 'COMPENSATED',
}
